#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

#echo 'I am a pre-commit'
#echo $(pwd)

echo '### (S) Updating Version Number ###'
Rscript .git/hooks/update-version.R
status=$?
if test $status -ne 0
then
	exit 1
else
  git add DESCRIPTION
fi
echo '### (F) Updating Version Number ###'
