#!/bin/sh
#

echo '### (S) Updating Version Number ###'
Rscript .git/hooks/update-version.R
status=$?
if test $status -ne 0
then
	exit 1
else
  git add DESCRIPTION
fi
echo '### (F) Updating Version Number ###'
